### ISSUE TITLE
Feature: add handler for root path /tracks

### ISSUE THREAD

**Issue by panaaj** [SignalK/tracks#3]
Add a handler for the root path ./tracks to return results for all vessels.
This functionality would allow a client to make one query at start up to retrieve all active vessels track rather then make multiple requests.

**Comment by tkurki** [comment]
I was just thinking about this the other day. What makes `tracks` special? What if I wanted to retrieve names, positions, headings and courses for all vessels?

**Comment by panaaj** [comment]
Not sure they are special... maybe just different! 
Tracks are more dynamic than a resource but not so dynamic as a measurement. They are kind of somewhere in between.

Currently I can use the path `./signalk/v1/api/vessels/` and get all of the data available for all vessels... but not the track.

So as it stands, if an app wants to display all vessels on a map with their server stored track at start up, or more importantly, after a user hits `refresh` it needs to:
1. Collate a list of all available vessels.... `HTTP GET  ./signalk/v1/api/vessels/`
2. For each vessel `HTTP GET  ./signalk/v1/api/vessels/<uuid>/track`

I see two immediate options (both may be problematic for different reasons):
1. Include  the `track` attribute and values in the `HTTP GET  ./signalk/v1/api/vessels/` response.
2. Make a path available that would return track values for all available vessels, similar to the response you get when you `HTTP GET  ./signalk/v1/api/resources/routes`, an object containing keys for each route and its value.... 
`e.g. ./signalk/v1/api/vessels/track`

**Comment by tkurki** [comment]
I don't think adding `track` to the full data is really feasible, as I think there is going to be more to track than jsut a default response. Imho it should be modeled more like an API with query params and less like _let's just put more stuff into this gigantic document_.  We really should be thinking about this in general terms, not just in the context of this particular plugin.

So in that way `/tracks` seems appropriate and there can be a default behavior that serves something sensible, albeit implementation dependent.

I recently connected to an AIS source that has data for the whole Norway. If we assume that the backend would be storing the track for all of them it would make sense to pass a bounding box of the current viewport to something sensible.

So what should the response look like? GeoJSON FeatureCollection, MultiLineString per vessel, with context in a property? Wanna take a stab at it?

**Comment by panaaj** [comment]
I've been thinking about this a bit further and was wondering (with regards to `default behavior that serves something sensible` and `AIS source that has data for the whole Norway`)...
One way to do this is set a default radius from the current vessel position as a filter for returned AIS targets.
This could be in the plugin or possibly even a server wide setting.

The argument for a server side setting is that the `other vessels` data available from the server is filtered for all apps not just those using the plugin. This also reduces the resource overhead on the server by limiting `other vessels` data and removes the need for any client filtering to keep resource usage down.

The API interface would still provide a bounding box parameter for efficiency when fetching vessel data.

As for the response, I'm not opposed to the GeoJSON FeatureCollection but this would be a departure from the current response format `{ vesselId: { .... }  }` and from `resources` path which uses a similar `{ resourceId: { .... }  }`.

As track is associated with a vessel it is similar to other vessel attributes so using GeoJSON FeatureCollection would be a departure OR is this the part of a greater v2 resource consideration...... currently resources are global could they be associated with vessels in future so maybe then the GeoJSON FeatureCollection is a better choice?

**Comment by panaaj** [comment]
Example of aligned output at `/tracks`:
```
{
	"urn:mrn:signalk:uuid:c0d79334-4e25-4245-8892-54e8ccc8021d": {
		"type": "MultiLineString",
		"coordinates": [
			[
				[138.5002485787992, -35.013353819075455],
				[138.50444062785664, -35.0129635439236],
				[138.50874067074028, -35.01283168748992]
			]
		]
	},
	"vessels.urn:mrn:signalk:uuid:16cd7ae3-248b-4304-8933-52abd72a03ff": {
		"type": "MultiLineString",
		"coordinates": [
			[
				[138.50001368081067, -34.999955988636096],
				[138.5007350964556, -34.997211762148524]
			]
		]
	}
}
```
